AllCops:
  Exclude:
    - vendor/**
    - bin/**
    - db/**
    - config/**
    - config/environments/**

Documentation:
  # don't require classes to be documented
  Enabled: false

Encoding:
  # no need to always specify encoding
  Enabled: false

AlignParameters:
  EnforcedStyle: with_fixed_indentation

Lint/EndAlignment:
  AlignWith: variable

ClassAndModuleChildren:
  Enabled: false
