db:
  image: postgres
  links:
    - elasticsearch
    - redis
  ports:
    - "5432:5432"
elasticsearch:
  image: elasticsearch
redis:
  image: redis
web:
  build: .
  command: bundle exec rails s -p 3000 -b '0.0.0.0' 
  ports:
    - "3000:3000"
  links:
    - db
  volumes:
    - .:/petpark
