default: &default
  adapter: postgresql
  reconnect: true
  host: localhost
  encoding: utf8
  username: brittanys
  
development: 
  <<: *default
  database: petpark
  port: 5432 

test:
  <<: *default
  database: petpark_test
  port: 5432 

production:
  <<: *default
  database: petpark 
