# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a96159ec465916a4904f6fd773da31a713571eed010d152df02028a189788d6b41b9a09354a4adb13a2acae84363bcc46275c7f15a2849c50e1403cb5e0958c

test:
  secret_key_base: 0148b8204d0f449a6da27a79d80f91de545fca38d4f63d3f0226978145d54b290de336e0c78ded57a43db8ba8d38ea546d5b53d2f2ab88228dab9098f0dd77bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
